### ISSUE TITLE
Add a Lead Rejection button 

### ISSUE THREAD

**Issue by devarsh** [devarsh/Ratnafin#167]
- Add a Lead Rejection button  (Mandate, Sanction, Bank Login, Leads Pages) and ask the reason for the cancellation
- Show the same in the Lead stages

**Comment by pithiyamilan** [comment]
API Details 
1] crm/inqiry/inactive
2] los/cold-calling/inactive
3] los/lead/inactive

Arguments refID and remarks and refresh the grid data.

**Comment by aayeshashaikh** [comment]
API call has done but the particular lead/inquiry/cold-calling data remain same in grid

**Comment by aayeshashaikh** [comment]
done
