### ISSUE TITLE
Add Loan Amount Validation

### ISSUE THREAD

**Issue by devarsh** [devarsh/Ratnafin#168]
**Prerequsit**
Need product-wise minimum loan amount 

- Loan amount provide validation for minimum Loan amount for all products in (Inquiry, Lead, Cold calling)

**Comment by pithiyamilan** [comment]
Date: 03-09-2021
Mail From: Poonam Dwivedi
Subject: Re: Need additional Requirement from your end to complete certain pending points.

Main Ans: Keep minimum loan amount restriction as rs.1.

Aayesha Add this restriction in Enquiry and Cold Calling, also Milan add for API Level Validation.

**Comment by aayeshashaikh** [comment]
The restriction has been applied on front-end and backend on both sides...
Need to replace the DB when we'll deploy the package.

**Comment by aayeshashaikh** [comment]
done
