### ISSUE TITLE
Add new Facility to resend Verification SMS Link for Validation API to end customers

### ISSUE THREAD

**Issue by devarsh** [devarsh/Ratnafin#169]
- Add option in Validation grid to resend SMS for Link that are still active

**Comment by sanjaysen9377** [comment]
**Required Additional facility has been added. see followings,**
- Resend SMS [If the request status: PENDING]
- Expire Request manually [If the request status: INITIATED/PENDING] 
- Re-Initiate the request [If the request status: FAILED]
